spring:
  application:
    name: task-management-system

  datasource:
    url: jdbc:postgresql://84.54.30.160:5432/test_db
#    url : jdbc:postgresql://localhost:5432/tms_db
    username: test_user
    password: 123_psw

      # Настройки пула Hikari
    hikari:
        # Максимальное время жизни соединения (28 минут).
        # Должно быть чуть меньше, чем таймаут на стороне самой БД.
        max-lifetime: 1680000

        # Таймаут ожидания соединения из пула (30 секунд)
        connection-timeout: 30000

        # Как долго держать простаивающее соединение перед удалением (10 минут)
        idle-timeout: 600000

        # Минимальное количество соединений, поддерживаемых в простое
        minimum-idle: 5

        # Максимальный размер пула
        maximum-pool-size: 10

        # Тест, который выполняется при проверке "живучести" соединения
        connection-test-query: SELECT 1


  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080

jwt:
  secret: ARNOABRAMIANIGORFURSOVLIZALAGEREVA
  expiration: 86400000  # 24 часа в миллисекундах

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.example: DEBUG
